// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AddANewUserHandlerFunc turns a function with the right signature into a add a new user handler
type AddANewUserHandlerFunc func(AddANewUserParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddANewUserHandlerFunc) Handle(params AddANewUserParams) middleware.Responder {
	return fn(params)
}

// AddANewUserHandler interface for that can handle valid add a new user params
type AddANewUserHandler interface {
	Handle(AddANewUserParams) middleware.Responder
}

// NewAddANewUser creates a new http.Handler for the add a new user operation
func NewAddANewUser(ctx *middleware.Context, handler AddANewUserHandler) *AddANewUser {
	return &AddANewUser{Context: ctx, Handler: handler}
}

/*AddANewUser swagger:route POST /users users addANewUser

Adds a new user configuration

Post a new user config

*/
type AddANewUser struct {
	Context *middleware.Context
	Handler AddANewUserHandler
}

func (o *AddANewUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddANewUserParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
