// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddANewUserCreatedCode is the HTTP code returned for type AddANewUserCreated
const AddANewUserCreatedCode int = 201

/*AddANewUserCreated Created

swagger:response addANewUserCreated
*/
type AddANewUserCreated struct {
}

// NewAddANewUserCreated creates AddANewUserCreated with default headers values
func NewAddANewUserCreated() *AddANewUserCreated {
	return &AddANewUserCreated{}
}

// WriteResponse to the client
func (o *AddANewUserCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
}

// AddANewUserBadRequestCode is the HTTP code returned for type AddANewUserBadRequest
const AddANewUserBadRequestCode int = 400

/*AddANewUserBadRequest Bad Request

swagger:response addANewUserBadRequest
*/
type AddANewUserBadRequest struct {
}

// NewAddANewUserBadRequest creates AddANewUserBadRequest with default headers values
func NewAddANewUserBadRequest() *AddANewUserBadRequest {
	return &AddANewUserBadRequest{}
}

// WriteResponse to the client
func (o *AddANewUserBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}
