// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteUserByIDNoContentCode is the HTTP code returned for type DeleteUserByIDNoContent
const DeleteUserByIDNoContentCode int = 204

/*DeleteUserByIDNoContent successful operation

swagger:response deleteUserByIdNoContent
*/
type DeleteUserByIDNoContent struct {
}

// NewDeleteUserByIDNoContent creates DeleteUserByIDNoContent with default headers values
func NewDeleteUserByIDNoContent() *DeleteUserByIDNoContent {

	return &DeleteUserByIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteUserByIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteUserByIDNotFoundCode is the HTTP code returned for type DeleteUserByIDNotFound
const DeleteUserByIDNotFoundCode int = 404

/*DeleteUserByIDNotFound Project not found

swagger:response deleteUserByIdNotFound
*/
type DeleteUserByIDNotFound struct {
}

// NewDeleteUserByIDNotFound creates DeleteUserByIDNotFound with default headers values
func NewDeleteUserByIDNotFound() *DeleteUserByIDNotFound {

	return &DeleteUserByIDNotFound{}
}

// WriteResponse to the client
func (o *DeleteUserByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
