// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddANewProjectCreatedCode is the HTTP code returned for type AddANewProjectCreated
const AddANewProjectCreatedCode int = 201

/*AddANewProjectCreated Created

swagger:response addANewProjectCreated
*/
type AddANewProjectCreated struct {
}

// NewAddANewProjectCreated creates AddANewProjectCreated with default headers values
func NewAddANewProjectCreated() *AddANewProjectCreated {
	return &AddANewProjectCreated{}
}

// WriteResponse to the client
func (o *AddANewProjectCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
}

// AddANewProjectBadRequestCode is the HTTP code returned for type AddANewProjectBadRequest
const AddANewProjectBadRequestCode int = 400

/*AddANewProjectBadRequest Bad Request

swagger:response addANewProjectBadRequest
*/
type AddANewProjectBadRequest struct {
}

// NewAddANewProjectBadRequest creates AddANewProjectBadRequest with default headers values
func NewAddANewProjectBadRequest() *AddANewProjectBadRequest {
	return &AddANewProjectBadRequest{}
}

// WriteResponse to the client
func (o *AddANewProjectBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}
