// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/king-jam/tracker2jira/rest/models"
)

// NewAddANewProjectParams creates a new AddANewProjectParams object
// with the default values initialized.
func NewAddANewProjectParams() AddANewProjectParams {
	var ()
	return AddANewProjectParams{}
}

// AddANewProjectParams contains all the bound params for the add a new project operation
// typically these are obtained from a http.Request
//
// swagger:parameters addANewProject
type AddANewProjectParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*Project definition
	  Required: true
	  In: body
	*/
	Body *models.Project
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *AddANewProjectParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Project
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body"))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}

	} else {
		res = append(res, errors.Required("body", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
