// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AddANewProjectHandlerFunc turns a function with the right signature into a add a new project handler
type AddANewProjectHandlerFunc func(AddANewProjectParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddANewProjectHandlerFunc) Handle(params AddANewProjectParams) middleware.Responder {
	return fn(params)
}

// AddANewProjectHandler interface for that can handle valid add a new project params
type AddANewProjectHandler interface {
	Handle(AddANewProjectParams) middleware.Responder
}

// NewAddANewProject creates a new http.Handler for the add a new project operation
func NewAddANewProject(ctx *middleware.Context, handler AddANewProjectHandler) *AddANewProject {
	return &AddANewProject{Context: ctx, Handler: handler}
}

/*AddANewProject swagger:route POST /projects projects addANewProject

Adds a project configuration

Post a new project config

*/
type AddANewProject struct {
	Context *middleware.Context
	Handler AddANewProjectHandler
}

func (o *AddANewProject) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddANewProjectParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
