// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddANewTaskCreatedCode is the HTTP code returned for type AddANewTaskCreated
const AddANewTaskCreatedCode int = 201

/*AddANewTaskCreated Created

swagger:response addANewTaskCreated
*/
type AddANewTaskCreated struct {
}

// NewAddANewTaskCreated creates AddANewTaskCreated with default headers values
func NewAddANewTaskCreated() *AddANewTaskCreated {
	return &AddANewTaskCreated{}
}

// WriteResponse to the client
func (o *AddANewTaskCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
}

// AddANewTaskBadRequestCode is the HTTP code returned for type AddANewTaskBadRequest
const AddANewTaskBadRequestCode int = 400

/*AddANewTaskBadRequest Bad Request

swagger:response addANewTaskBadRequest
*/
type AddANewTaskBadRequest struct {
}

// NewAddANewTaskBadRequest creates AddANewTaskBadRequest with default headers values
func NewAddANewTaskBadRequest() *AddANewTaskBadRequest {
	return &AddANewTaskBadRequest{}
}

// WriteResponse to the client
func (o *AddANewTaskBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}
