// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/king-jam/tracker2jira/rest/models"
)

// GetProjectByIDOKCode is the HTTP code returned for type GetProjectByIDOK
const GetProjectByIDOKCode int = 200

/*GetProjectByIDOK successful operation

swagger:response getProjectByIdOK
*/
type GetProjectByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Project `json:"body,omitempty"`
}

// NewGetProjectByIDOK creates GetProjectByIDOK with default headers values
func NewGetProjectByIDOK() *GetProjectByIDOK {
	return &GetProjectByIDOK{}
}

// WithPayload adds the payload to the get project by Id o k response
func (o *GetProjectByIDOK) WithPayload(payload *models.Project) *GetProjectByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get project by Id o k response
func (o *GetProjectByIDOK) SetPayload(payload *models.Project) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProjectByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetProjectByIDNotFoundCode is the HTTP code returned for type GetProjectByIDNotFound
const GetProjectByIDNotFoundCode int = 404

/*GetProjectByIDNotFound Project not found

swagger:response getProjectByIdNotFound
*/
type GetProjectByIDNotFound struct {
}

// NewGetProjectByIDNotFound creates GetProjectByIDNotFound with default headers values
func NewGetProjectByIDNotFound() *GetProjectByIDNotFound {
	return &GetProjectByIDNotFound{}
}

// WriteResponse to the client
func (o *GetProjectByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}
