// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTaskByIDParams creates a new GetTaskByIDParams object
// with the default values initialized.
func NewGetTaskByIDParams() GetTaskByIDParams {
	var ()
	return GetTaskByIDParams{}
}

// GetTaskByIDParams contains all the bound params for the get task by ID operation
// typically these are obtained from a http.Request
//
// swagger:parameters getTaskByID
type GetTaskByIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*ID of task to return
	  Required: true
	  In: path
	*/
	TaskID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetTaskByIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rTaskID, rhkTaskID, _ := route.Params.GetOK("taskID")
	if err := o.bindTaskID(rTaskID, rhkTaskID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetTaskByIDParams) bindTaskID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.TaskID = raw

	return nil
}
