// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/king-jam/tracker2jira/rest/models"
)

// GetProjectsOKCode is the HTTP code returned for type GetProjectsOK
const GetProjectsOKCode int = 200

/*GetProjectsOK The list of current projects

swagger:response getProjectsOK
*/
type GetProjectsOK struct {

	/*
	  In: Body
	*/
	Payload models.Projects `json:"body,omitempty"`
}

// NewGetProjectsOK creates GetProjectsOK with default headers values
func NewGetProjectsOK() *GetProjectsOK {

	return &GetProjectsOK{}
}

// WithPayload adds the payload to the get projects o k response
func (o *GetProjectsOK) WithPayload(payload models.Projects) *GetProjectsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get projects o k response
func (o *GetProjectsOK) SetPayload(payload models.Projects) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProjectsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.Projects, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetProjectsBadRequestCode is the HTTP code returned for type GetProjectsBadRequest
const GetProjectsBadRequestCode int = 400

/*GetProjectsBadRequest Bad Request

swagger:response getProjectsBadRequest
*/
type GetProjectsBadRequest struct {
}

// NewGetProjectsBadRequest creates GetProjectsBadRequest with default headers values
func NewGetProjectsBadRequest() *GetProjectsBadRequest {

	return &GetProjectsBadRequest{}
}

// WriteResponse to the client
func (o *GetProjectsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
