// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetProjectByIDHandlerFunc turns a function with the right signature into a get project by ID handler
type GetProjectByIDHandlerFunc func(GetProjectByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetProjectByIDHandlerFunc) Handle(params GetProjectByIDParams) middleware.Responder {
	return fn(params)
}

// GetProjectByIDHandler interface for that can handle valid get project by ID params
type GetProjectByIDHandler interface {
	Handle(GetProjectByIDParams) middleware.Responder
}

// NewGetProjectByID creates a new http.Handler for the get project by ID operation
func NewGetProjectByID(ctx *middleware.Context, handler GetProjectByIDHandler) *GetProjectByID {
	return &GetProjectByID{Context: ctx, Handler: handler}
}

/*GetProjectByID swagger:route GET /projects/{projectID} projects getProjectById

gets the project from ID

getting project object

*/
type GetProjectByID struct {
	Context *middleware.Context
	Handler GetProjectByIDHandler
}

func (o *GetProjectByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetProjectByIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
