// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostProjectCreatedCode is the HTTP code returned for type PostProjectCreated
const PostProjectCreatedCode int = 201

/*PostProjectCreated Created

swagger:response postProjectCreated
*/
type PostProjectCreated struct {
}

// NewPostProjectCreated creates PostProjectCreated with default headers values
func NewPostProjectCreated() *PostProjectCreated {
	return &PostProjectCreated{}
}

// WriteResponse to the client
func (o *PostProjectCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
}

// PostProjectBadRequestCode is the HTTP code returned for type PostProjectBadRequest
const PostProjectBadRequestCode int = 400

/*PostProjectBadRequest Bad Request

swagger:response postProjectBadRequest
*/
type PostProjectBadRequest struct {
}

// NewPostProjectBadRequest creates PostProjectBadRequest with default headers values
func NewPostProjectBadRequest() *PostProjectBadRequest {
	return &PostProjectBadRequest{}
}

// WriteResponse to the client
func (o *PostProjectBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}
