// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// AddANewProjectReader is a Reader for the AddANewProject structure.
type AddANewProjectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddANewProjectReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewAddANewProjectCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewAddANewProjectBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAddANewProjectCreated creates a AddANewProjectCreated with default headers values
func NewAddANewProjectCreated() *AddANewProjectCreated {
	return &AddANewProjectCreated{}
}

/*AddANewProjectCreated handles this case with default header values.

Created
*/
type AddANewProjectCreated struct {
}

func (o *AddANewProjectCreated) Error() string {
	return fmt.Sprintf("[POST /projects][%d] addANewProjectCreated ", 201)
}

func (o *AddANewProjectCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddANewProjectBadRequest creates a AddANewProjectBadRequest with default headers values
func NewAddANewProjectBadRequest() *AddANewProjectBadRequest {
	return &AddANewProjectBadRequest{}
}

/*AddANewProjectBadRequest handles this case with default header values.

Bad Request
*/
type AddANewProjectBadRequest struct {
}

func (o *AddANewProjectBadRequest) Error() string {
	return fmt.Sprintf("[POST /projects][%d] addANewProjectBadRequest ", 400)
}

func (o *AddANewProjectBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
