// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/king-jam/tracker2jira/rest/models"
)

// NewAddANewTaskParams creates a new AddANewTaskParams object
// with the default values initialized.
func NewAddANewTaskParams() *AddANewTaskParams {
	var ()
	return &AddANewTaskParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddANewTaskParamsWithTimeout creates a new AddANewTaskParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddANewTaskParamsWithTimeout(timeout time.Duration) *AddANewTaskParams {
	var ()
	return &AddANewTaskParams{

		timeout: timeout,
	}
}

// NewAddANewTaskParamsWithContext creates a new AddANewTaskParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddANewTaskParamsWithContext(ctx context.Context) *AddANewTaskParams {
	var ()
	return &AddANewTaskParams{

		Context: ctx,
	}
}

// NewAddANewTaskParamsWithHTTPClient creates a new AddANewTaskParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddANewTaskParamsWithHTTPClient(client *http.Client) *AddANewTaskParams {
	var ()
	return &AddANewTaskParams{
		HTTPClient: client,
	}
}

/*AddANewTaskParams contains all the parameters to send to the API endpoint
for the add a new task operation typically these are written to a http.Request
*/
type AddANewTaskParams struct {

	/*Body
	  Task definition

	*/
	Body *models.Task

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add a new task params
func (o *AddANewTaskParams) WithTimeout(timeout time.Duration) *AddANewTaskParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add a new task params
func (o *AddANewTaskParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add a new task params
func (o *AddANewTaskParams) WithContext(ctx context.Context) *AddANewTaskParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add a new task params
func (o *AddANewTaskParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add a new task params
func (o *AddANewTaskParams) WithHTTPClient(client *http.Client) *AddANewTaskParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add a new task params
func (o *AddANewTaskParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add a new task params
func (o *AddANewTaskParams) WithBody(body *models.Task) *AddANewTaskParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add a new task params
func (o *AddANewTaskParams) SetBody(body *models.Task) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AddANewTaskParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
