// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/king-jam/tracker2jira/rest/models"
)

// NewAddANewProjectParams creates a new AddANewProjectParams object
// with the default values initialized.
func NewAddANewProjectParams() *AddANewProjectParams {
	var ()
	return &AddANewProjectParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddANewProjectParamsWithTimeout creates a new AddANewProjectParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddANewProjectParamsWithTimeout(timeout time.Duration) *AddANewProjectParams {
	var ()
	return &AddANewProjectParams{

		timeout: timeout,
	}
}

// NewAddANewProjectParamsWithContext creates a new AddANewProjectParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddANewProjectParamsWithContext(ctx context.Context) *AddANewProjectParams {
	var ()
	return &AddANewProjectParams{

		Context: ctx,
	}
}

// NewAddANewProjectParamsWithHTTPClient creates a new AddANewProjectParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddANewProjectParamsWithHTTPClient(client *http.Client) *AddANewProjectParams {
	var ()
	return &AddANewProjectParams{
		HTTPClient: client,
	}
}

/*AddANewProjectParams contains all the parameters to send to the API endpoint
for the add a new project operation typically these are written to a http.Request
*/
type AddANewProjectParams struct {

	/*Body
	  Project definition

	*/
	Body *models.Project

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add a new project params
func (o *AddANewProjectParams) WithTimeout(timeout time.Duration) *AddANewProjectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add a new project params
func (o *AddANewProjectParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add a new project params
func (o *AddANewProjectParams) WithContext(ctx context.Context) *AddANewProjectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add a new project params
func (o *AddANewProjectParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add a new project params
func (o *AddANewProjectParams) WithHTTPClient(client *http.Client) *AddANewProjectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add a new project params
func (o *AddANewProjectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add a new project params
func (o *AddANewProjectParams) WithBody(body *models.Project) *AddANewProjectParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add a new project params
func (o *AddANewProjectParams) SetBody(body *models.Project) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AddANewProjectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
