// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostProjectReader is a Reader for the PostProject structure.
type PostProjectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostProjectReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostProjectCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostProjectBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostProjectCreated creates a PostProjectCreated with default headers values
func NewPostProjectCreated() *PostProjectCreated {
	return &PostProjectCreated{}
}

/*PostProjectCreated handles this case with default header values.

Created
*/
type PostProjectCreated struct {
}

func (o *PostProjectCreated) Error() string {
	return fmt.Sprintf("[POST /projects][%d] postProjectCreated ", 201)
}

func (o *PostProjectCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostProjectBadRequest creates a PostProjectBadRequest with default headers values
func NewPostProjectBadRequest() *PostProjectBadRequest {
	return &PostProjectBadRequest{}
}

/*PostProjectBadRequest handles this case with default header values.

Bad Request
*/
type PostProjectBadRequest struct {
}

func (o *PostProjectBadRequest) Error() string {
	return fmt.Sprintf("[POST /projects][%d] postProjectBadRequest ", 400)
}

func (o *PostProjectBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
