# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/andygrunwald/go-jira"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/carbocation/interpose"

[[constraint]]
  name = "github.com/docker/libkv"
  version = "0.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/elazarl/go-bindata-assetfs"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/errors"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/loads"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/runtime"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/spec"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/strfmt"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/swag"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/validate"

[[constraint]]
  branch = "master"
  name = "github.com/king-jam/go-pivotaltracker"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"

[[constraint]]
  name = "github.com/tylerb/graceful"
  version = "1.2.15"
