// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	security "github.com/go-openapi/runtime/security"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/king-jam/tracker2jira/rest/server/operations/general"
	"github.com/king-jam/tracker2jira/rest/server/operations/projects"
	"github.com/king-jam/tracker2jira/rest/server/operations/users"
)

// NewT2jAPI creates a new T2j instance
func NewT2jAPI(spec *loads.Document) *T2jAPI {
	return &T2jAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		ServerShutdown:      func() {},
		spec:                spec,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,
		JSONConsumer:        runtime.JSONConsumer(),
		JSONProducer:        runtime.JSONProducer(),
		ProjectsGetProjectByIDHandler: projects.GetProjectByIDHandlerFunc(func(params projects.GetProjectByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation ProjectsGetProjectByID has not yet been implemented")
		}),
		ProjectsGetProjectsHandler: projects.GetProjectsHandlerFunc(func(params projects.GetProjectsParams) middleware.Responder {
			return middleware.NotImplemented("operation ProjectsGetProjects has not yet been implemented")
		}),
		ProjectsGetTaskByIDHandler: projects.GetTaskByIDHandlerFunc(func(params projects.GetTaskByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation ProjectsGetTaskByID has not yet been implemented")
		}),
		ProjectsGetTasksHandler: projects.GetTasksHandlerFunc(func(params projects.GetTasksParams) middleware.Responder {
			return middleware.NotImplemented("operation ProjectsGetTasks has not yet been implemented")
		}),
		UsersGetUserByIDHandler: users.GetUserByIDHandlerFunc(func(params users.GetUserByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation UsersGetUserByID has not yet been implemented")
		}),
		UsersGetUsersHandler: users.GetUsersHandlerFunc(func(params users.GetUsersParams) middleware.Responder {
			return middleware.NotImplemented("operation UsersGetUsers has not yet been implemented")
		}),
		ProjectsPostProjectHandler: projects.PostProjectHandlerFunc(func(params projects.PostProjectParams) middleware.Responder {
			return middleware.NotImplemented("operation ProjectsPostProject has not yet been implemented")
		}),
		ProjectsPostTaskHandler: projects.PostTaskHandlerFunc(func(params projects.PostTaskParams) middleware.Responder {
			return middleware.NotImplemented("operation ProjectsPostTask has not yet been implemented")
		}),
		UsersPostUserHandler: users.PostUserHandlerFunc(func(params users.PostUserParams) middleware.Responder {
			return middleware.NotImplemented("operation UsersPostUser has not yet been implemented")
		}),
		GeneralRootHandler: general.RootHandlerFunc(func(params general.RootParams) middleware.Responder {
			return middleware.NotImplemented("operation GeneralRoot has not yet been implemented")
		}),
		GeneralVersionHandler: general.VersionHandlerFunc(func(params general.VersionParams) middleware.Responder {
			return middleware.NotImplemented("operation GeneralVersion has not yet been implemented")
		}),
	}
}

/*T2jAPI Pivotal Tracker to JIRA synchronization service. */
type T2jAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer

	// ProjectsGetProjectByIDHandler sets the operation handler for the get project by ID operation
	ProjectsGetProjectByIDHandler projects.GetProjectByIDHandler
	// ProjectsGetProjectsHandler sets the operation handler for the get projects operation
	ProjectsGetProjectsHandler projects.GetProjectsHandler
	// ProjectsGetTaskByIDHandler sets the operation handler for the get task by ID operation
	ProjectsGetTaskByIDHandler projects.GetTaskByIDHandler
	// ProjectsGetTasksHandler sets the operation handler for the get tasks operation
	ProjectsGetTasksHandler projects.GetTasksHandler
	// UsersGetUserByIDHandler sets the operation handler for the get user by ID operation
	UsersGetUserByIDHandler users.GetUserByIDHandler
	// UsersGetUsersHandler sets the operation handler for the get users operation
	UsersGetUsersHandler users.GetUsersHandler
	// ProjectsPostProjectHandler sets the operation handler for the post project operation
	ProjectsPostProjectHandler projects.PostProjectHandler
	// ProjectsPostTaskHandler sets the operation handler for the post task operation
	ProjectsPostTaskHandler projects.PostTaskHandler
	// UsersPostUserHandler sets the operation handler for the post user operation
	UsersPostUserHandler users.PostUserHandler
	// GeneralRootHandler sets the operation handler for the root operation
	GeneralRootHandler general.RootHandler
	// GeneralVersionHandler sets the operation handler for the version operation
	GeneralVersionHandler general.VersionHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *T2jAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *T2jAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *T2jAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *T2jAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *T2jAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *T2jAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *T2jAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the T2jAPI
func (o *T2jAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.ProjectsGetProjectByIDHandler == nil {
		unregistered = append(unregistered, "projects.GetProjectByIDHandler")
	}

	if o.ProjectsGetProjectsHandler == nil {
		unregistered = append(unregistered, "projects.GetProjectsHandler")
	}

	if o.ProjectsGetTaskByIDHandler == nil {
		unregistered = append(unregistered, "projects.GetTaskByIDHandler")
	}

	if o.ProjectsGetTasksHandler == nil {
		unregistered = append(unregistered, "projects.GetTasksHandler")
	}

	if o.UsersGetUserByIDHandler == nil {
		unregistered = append(unregistered, "users.GetUserByIDHandler")
	}

	if o.UsersGetUsersHandler == nil {
		unregistered = append(unregistered, "users.GetUsersHandler")
	}

	if o.ProjectsPostProjectHandler == nil {
		unregistered = append(unregistered, "projects.PostProjectHandler")
	}

	if o.ProjectsPostTaskHandler == nil {
		unregistered = append(unregistered, "projects.PostTaskHandler")
	}

	if o.UsersPostUserHandler == nil {
		unregistered = append(unregistered, "users.PostUserHandler")
	}

	if o.GeneralRootHandler == nil {
		unregistered = append(unregistered, "general.RootHandler")
	}

	if o.GeneralVersionHandler == nil {
		unregistered = append(unregistered, "general.VersionHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *T2jAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *T2jAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	return nil

}

// Authorizer returns the registered authorizer
func (o *T2jAPI) Authorizer() runtime.Authorizer {

	return nil

}

// ConsumersFor gets the consumers for the specified media types
func (o *T2jAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *T2jAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *T2jAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the t2j API
func (o *T2jAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *T2jAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/projects/{projectID}"] = projects.NewGetProjectByID(o.context, o.ProjectsGetProjectByIDHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/projects"] = projects.NewGetProjects(o.context, o.ProjectsGetProjectsHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/tasks/{taskID}"] = projects.NewGetTaskByID(o.context, o.ProjectsGetTaskByIDHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/tasks"] = projects.NewGetTasks(o.context, o.ProjectsGetTasksHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/users/{userID}"] = users.NewGetUserByID(o.context, o.UsersGetUserByIDHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/users"] = users.NewGetUsers(o.context, o.UsersGetUsersHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/projects"] = projects.NewPostProject(o.context, o.ProjectsPostProjectHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/tasks"] = projects.NewPostTask(o.context, o.ProjectsPostTaskHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/users"] = users.NewPostUser(o.context, o.UsersPostUserHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"][""] = general.NewRoot(o.context, o.GeneralRootHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/version"] = general.NewVersion(o.context, o.GeneralVersionHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *T2jAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middelware as you see fit
func (o *T2jAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}
