// Code generated by go-swagger; DO NOT EDIT.

package general

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// RootOKCode is the HTTP code returned for type RootOK
const RootOKCode int = 200

/*RootOK Successfully returned the default UI.

swagger:response rootOK
*/
type RootOK struct {
}

// NewRootOK creates RootOK with default headers values
func NewRootOK() *RootOK {
	return &RootOK{}
}

// WriteResponse to the client
func (o *RootOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}
