// Code generated by go-swagger; DO NOT EDIT.

package general

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// VersionOKCode is the HTTP code returned for type VersionOK
const VersionOKCode int = 200

/*VersionOK The current version of the service

swagger:response versionOK
*/
type VersionOK struct {
}

// NewVersionOK creates VersionOK with default headers values
func NewVersionOK() *VersionOK {
	return &VersionOK{}
}

// WriteResponse to the client
func (o *VersionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}
