// Code generated by go-swagger; DO NOT EDIT.

package server

import (
	"crypto/tls"
	"net/http"

	errors "github.com/go-openapi/errors"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	graceful "github.com/tylerb/graceful"

	"github.com/king-jam/tracker2jira/rest/server/operations"
	"github.com/king-jam/tracker2jira/rest/server/operations/general"
	"github.com/king-jam/tracker2jira/rest/server/operations/projects"
	"github.com/king-jam/tracker2jira/rest/server/operations/users"
)

// This file is safe to edit. Once it exists it will not be overwritten

//go:generate swagger generate server --target .. --name t2j --spec ../swagger.yaml --server-package server --exclude-main

func configureFlags(api *operations.T2jAPI) {
	// api.CommandLineOptionsGroups = []swag.CommandLineOptionsGroup{ ... }
}

func configureAPI(api *operations.T2jAPI) http.Handler {
	// configure the api here
	api.ServeError = errors.ServeError

	// Set your custom logger if needed. Default one is log.Printf
	// Expected interface func(string, ...interface{})
	//
	// Example:
	// api.Logger = log.Printf

	api.JSONConsumer = runtime.JSONConsumer()

	api.JSONProducer = runtime.JSONProducer()

	api.ProjectsGetProjectByIDHandler = projects.GetProjectByIDHandlerFunc(func(params projects.GetProjectByIDParams) middleware.Responder {
		return middleware.NotImplemented("operation projects.GetProjectByID has not yet been implemented")
	})
	api.ProjectsGetProjectsHandler = projects.GetProjectsHandlerFunc(func(params projects.GetProjectsParams) middleware.Responder {
		return middleware.NotImplemented("operation projects.GetProjects has not yet been implemented")
	})
	api.ProjectsGetTaskByIDHandler = projects.GetTaskByIDHandlerFunc(func(params projects.GetTaskByIDParams) middleware.Responder {
		return middleware.NotImplemented("operation projects.GetTaskByID has not yet been implemented")
	})
	api.ProjectsGetTasksHandler = projects.GetTasksHandlerFunc(func(params projects.GetTasksParams) middleware.Responder {
		return middleware.NotImplemented("operation projects.GetTasks has not yet been implemented")
	})
	api.UsersGetUserByIDHandler = users.GetUserByIDHandlerFunc(func(params users.GetUserByIDParams) middleware.Responder {
		return middleware.NotImplemented("operation users.GetUserByID has not yet been implemented")
	})
	api.UsersGetUsersHandler = users.GetUsersHandlerFunc(func(params users.GetUsersParams) middleware.Responder {
		return middleware.NotImplemented("operation users.GetUsers has not yet been implemented")
	})
	api.ProjectsPostProjectHandler = projects.PostProjectHandlerFunc(func(params projects.PostProjectParams) middleware.Responder {
		return middleware.NotImplemented("operation projects.PostProject has not yet been implemented")
	})
	api.ProjectsPostTaskHandler = projects.PostTaskHandlerFunc(func(params projects.PostTaskParams) middleware.Responder {
		return middleware.NotImplemented("operation projects.PostTask has not yet been implemented")
	})
	api.UsersPostUserHandler = users.PostUserHandlerFunc(func(params users.PostUserParams) middleware.Responder {
		return middleware.NotImplemented("operation users.PostUser has not yet been implemented")
	})
	api.GeneralRootHandler = general.RootHandlerFunc(func(params general.RootParams) middleware.Responder {
		return middleware.NotImplemented("operation general.Root has not yet been implemented")
	})
	api.GeneralVersionHandler = general.VersionHandlerFunc(func(params general.VersionParams) middleware.Responder {
		return middleware.NotImplemented("operation general.Version has not yet been implemented")
	})

	api.ServerShutdown = func() {}

	return setupGlobalMiddleware(api.Serve(setupMiddlewares))
}

// The TLS configuration before HTTPS server starts.
func configureTLS(tlsConfig *tls.Config) {
	// Make all necessary changes to the TLS configuration here.
}

// As soon as server is initialized but not run yet, this function will be called.
// If you need to modify a config, store server instance to stop it individually later, this is the place.
// This function can be called multiple times, depending on the number of serving schemes.
// scheme value will be set accordingly: "http", "https" or "unix"
func configureServer(s *graceful.Server, scheme, addr string) {
}

// The middleware configuration is for the handler executors. These do not apply to the swagger.json document.
// The middleware executes after routing but before authentication, binding and validation
func setupMiddlewares(handler http.Handler) http.Handler {
	return handler
}

// The middleware configuration happens before anything, this middleware also applies to serving the swagger.json document.
// So this is a good place to plug in a panic handling middleware, logging and metrics
func setupGlobalMiddleware(handler http.Handler) http.Handler {
	return handler
}
