// Code generated by go-swagger; DO NOT EDIT.

package server

import (
	"crypto/tls"
	"net/http"

	errors "github.com/go-openapi/errors"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	graceful "github.com/tylerb/graceful"

	"github.com/king-jam/tracker2jira/rest/server/operations"
	"github.com/king-jam/tracker2jira/rest/server/operations/general"
)

// This file is safe to edit. Once it exists it will not be overwritten

//go:generate swagger generate server --target .. --name t2j --spec ../swagger.yaml --server-package server --exclude-main

func configureFlags(api *operations.T2jAPI) {
	// api.CommandLineOptionsGroups = []swag.CommandLineOptionsGroup{ ... }
}

func configureAPI(api *operations.T2jAPI) http.Handler {
	// configure the api here
	api.ServeError = errors.ServeError

	// Set your custom logger if needed. Default one is log.Printf
	// Expected interface func(string, ...interface{})
	//
	// Example:
	// api.Logger = log.Printf

	api.JSONConsumer = runtime.JSONConsumer()

	api.JSONProducer = runtime.JSONProducer()

	api.GeneralGetConfigHandler = general.GetConfigHandlerFunc(func(params general.GetConfigParams) middleware.Responder {
		return middleware.NotImplemented("operation general.GetConfig has not yet been implemented")
	})
	api.GeneralPatchConfigHandler = general.PatchConfigHandlerFunc(func(params general.PatchConfigParams) middleware.Responder {
		return middleware.NotImplemented("operation general.PatchConfig has not yet been implemented")
	})
	api.GeneralLoginHandler = general.LoginHandlerFunc(func(params general.LoginParams) middleware.Responder {
		return middleware.NotImplemented("operation general.Login has not yet been implemented")
	})
	api.GeneralRootHandler = general.RootHandlerFunc(func(params general.RootParams) middleware.Responder {
		return middleware.NotImplemented("operation general.Root has not yet been implemented")
	})
	api.GeneralVersionHandler = general.VersionHandlerFunc(func(params general.VersionParams) middleware.Responder {
		return middleware.NotImplemented("operation general.Version has not yet been implemented")
	})

	api.ServerShutdown = func() {}

	return setupGlobalMiddleware(api.Serve(setupMiddlewares))
}

// The TLS configuration before HTTPS server starts.
func configureTLS(tlsConfig *tls.Config) {
	// Make all necessary changes to the TLS configuration here.
}

// As soon as server is initialized but not run yet, this function will be called.
// If you need to modify a config, store server instance to stop it individually later, this is the place.
// This function can be called multiple times, depending on the number of serving schemes.
// scheme value will be set accordingly: "http", "https" or "unix"
func configureServer(s *graceful.Server, scheme, addr string) {
}

// The middleware configuration is for the handler executors. These do not apply to the swagger.json document.
// The middleware executes after routing but before authentication, binding and validation
func setupMiddlewares(handler http.Handler) http.Handler {
	return handler
}

// The middleware configuration happens before anything, this middleware also applies to serving the swagger.json document.
// So this is a good place to plug in a panic handling middleware, logging and metrics
func setupGlobalMiddleware(handler http.Handler) http.Handler {
	return handler
}
