// Code generated by go-swagger; DO NOT EDIT.

/*
Package server Tracker 2 JIRA
Pivotal Tracker to JIRA synchronization service.

Terms Of Service:

https://github.com/king-jam/tracker2jira/blob/master/docs/TOS.md


    Schemes:
      http
      https
    Host: localhost
    BasePath: /
    Version: 0.0.1
    License: Mozilla Public License 2.0 https://www.mozilla.org/en-US/MPL/2.0/
    Contact: <james.r.king4@gmail.com>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package server
