// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Placeholder for the desscription of this thing.",
    "title": "Tracker 2 JIRA",
    "termsOfService": "https://github.com/king-jam/tracker2jira/blob/master/docs/TOS.md",
    "contact": {
      "email": "james.r.king4@gmail.com"
    },
    "license": {
      "name": "Mozilla Public License 2.0",
      "url": "https://www.mozilla.org/en-US/MPL/2.0/"
    },
    "version": "0.0.1"
  },
  "basePath": "/t2j",
  "paths": {
    "/": {
      "get": {
        "tags": [
          "general"
        ],
        "summary": "Returns the default home page",
        "operationId": "root",
        "responses": {
          "200": {
            "description": "The default home page for the application"
          }
        }
      }
    },
    "/config": {
      "get": {
        "tags": [
          "general"
        ],
        "summary": "Get the current running configuration",
        "responses": {
          "200": {
            "description": "The current configuration"
          }
        }
      },
      "patch": {
        "tags": [
          "general"
        ],
        "summary": "Update the current running configuration",
        "responses": {
          "200": {
            "description": "Configuration Changed"
          }
        }
      }
    },
    "/login": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "tags": [
          "general"
        ],
        "summary": "Logs in and returns authentication type based on parameters",
        "operationId": "login",
        "parameters": [
          {
            "description": "A JSON obect containing the login and password",
            "name": "loginRequest",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/LoginRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Login"
          },
          "400": {
            "description": "Invalid username/password"
          }
        }
      }
    },
    "/version": {
      "get": {
        "tags": [
          "general"
        ],
        "summary": "Returns the current version running.",
        "operationId": "version",
        "responses": {
          "200": {
            "description": "The current version of the service"
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "LoginRequest": {
      "description": "Login Request Body",
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      }
    }
  },
  "responses": {
    "NotFound": {
      "description": "The specified resource was not found",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "Unauthorized": {
      "description": "Unauthorized",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    }
  },
  "securityDefinitions": {
    "ApiKeyAuth": {
      "type": "apiKey",
      "name": "X-API-Key",
      "in": "header"
    }
  },
  "tags": [
    {
      "description": "General Application Settings \u0026 Information",
      "name": "general",
      "externalDocs": {
        "description": "Documentation",
        "url": "https://github.com/king-jam/tracker2jira/blob/master/docs/README.md"
      }
    },
    {
      "description": "Project configurations that are under management",
      "name": "projects"
    },
    {
      "description": "Operations about project members",
      "name": "users"
    }
  ]
}`))
}
