// Code generated by go-swagger; DO NOT EDIT.

package general

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// RootReader is a Reader for the Root structure.
type RootReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RootReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewRootOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRootOK creates a RootOK with default headers values
func NewRootOK() *RootOK {
	return &RootOK{}
}

/*RootOK handles this case with default header values.

The default home page for the application
*/
type RootOK struct {
}

func (o *RootOK) Error() string {
	return fmt.Sprintf("[GET /][%d] rootOK ", 200)
}

func (o *RootOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
