// Code generated by go-swagger; DO NOT EDIT.

package tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteTaskByIDHandlerFunc turns a function with the right signature into a delete task by ID handler
type DeleteTaskByIDHandlerFunc func(DeleteTaskByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteTaskByIDHandlerFunc) Handle(params DeleteTaskByIDParams) middleware.Responder {
	return fn(params)
}

// DeleteTaskByIDHandler interface for that can handle valid delete task by ID params
type DeleteTaskByIDHandler interface {
	Handle(DeleteTaskByIDParams) middleware.Responder
}

// NewDeleteTaskByID creates a new http.Handler for the delete task by ID operation
func NewDeleteTaskByID(ctx *middleware.Context, handler DeleteTaskByIDHandler) *DeleteTaskByID {
	return &DeleteTaskByID{Context: ctx, Handler: handler}
}

/*DeleteTaskByID swagger:route DELETE /tasks/{taskID} tasks deleteTaskById

Delete the Task by ID

Delete the task object.

*/
type DeleteTaskByID struct {
	Context *middleware.Context
	Handler DeleteTaskByIDHandler
}

func (o *DeleteTaskByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteTaskByIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
