// Code generated by go-swagger; DO NOT EDIT.

package tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteTaskByIDNoContentCode is the HTTP code returned for type DeleteTaskByIDNoContent
const DeleteTaskByIDNoContentCode int = 204

/*DeleteTaskByIDNoContent successful operation

swagger:response deleteTaskByIdNoContent
*/
type DeleteTaskByIDNoContent struct {
}

// NewDeleteTaskByIDNoContent creates DeleteTaskByIDNoContent with default headers values
func NewDeleteTaskByIDNoContent() *DeleteTaskByIDNoContent {
	return &DeleteTaskByIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteTaskByIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}

// DeleteTaskByIDNotFoundCode is the HTTP code returned for type DeleteTaskByIDNotFound
const DeleteTaskByIDNotFoundCode int = 404

/*DeleteTaskByIDNotFound Project not found

swagger:response deleteTaskByIdNotFound
*/
type DeleteTaskByIDNotFound struct {
}

// NewDeleteTaskByIDNotFound creates DeleteTaskByIDNotFound with default headers values
func NewDeleteTaskByIDNotFound() *DeleteTaskByIDNotFound {
	return &DeleteTaskByIDNotFound{}
}

// WriteResponse to the client
func (o *DeleteTaskByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}
