// Code generated by go-swagger; DO NOT EDIT.

package tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/king-jam/tracker2jira/rest/models"
)

// GetTasksOKCode is the HTTP code returned for type GetTasksOK
const GetTasksOKCode int = 200

/*GetTasksOK The list of current tasks

swagger:response getTasksOK
*/
type GetTasksOK struct {

	/*
	  In: Body
	*/
	Payload models.Tasks `json:"body,omitempty"`
}

// NewGetTasksOK creates GetTasksOK with default headers values
func NewGetTasksOK() *GetTasksOK {
	return &GetTasksOK{}
}

// WithPayload adds the payload to the get tasks o k response
func (o *GetTasksOK) WithPayload(payload models.Tasks) *GetTasksOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tasks o k response
func (o *GetTasksOK) SetPayload(payload models.Tasks) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTasksOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.Tasks, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetTasksBadRequestCode is the HTTP code returned for type GetTasksBadRequest
const GetTasksBadRequestCode int = 400

/*GetTasksBadRequest Bad Request

swagger:response getTasksBadRequest
*/
type GetTasksBadRequest struct {
}

// NewGetTasksBadRequest creates GetTasksBadRequest with default headers values
func NewGetTasksBadRequest() *GetTasksBadRequest {
	return &GetTasksBadRequest{}
}

// WriteResponse to the client
func (o *GetTasksBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
