// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Credentials credentials
// swagger:model Credentials
type Credentials struct {

	// password
	Password string `json:"password,omitempty"`

	// token
	Token string `json:"token,omitempty"`

	// type
	Type string `json:"type,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this credentials
func (m *Credentials) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var credentialsTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["jira_basic","jira_oauth","tracker_token"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		credentialsTypeTypePropEnum = append(credentialsTypeTypePropEnum, v)
	}
}

const (
	// CredentialsTypeJiraBasic captures enum value "jira_basic"
	CredentialsTypeJiraBasic string = "jira_basic"
	// CredentialsTypeJiraOauth captures enum value "jira_oauth"
	CredentialsTypeJiraOauth string = "jira_oauth"
	// CredentialsTypeTrackerToken captures enum value "tracker_token"
	CredentialsTypeTrackerToken string = "tracker_token"
)

// prop value enum
func (m *Credentials) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, credentialsTypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *Credentials) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Credentials) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Credentials) UnmarshalBinary(b []byte) error {
	var res Credentials
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
