// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/king-jam/tracker2jira/rest/models"
)

// NewAddANewUserParams creates a new AddANewUserParams object
// with the default values initialized.
func NewAddANewUserParams() *AddANewUserParams {
	var ()
	return &AddANewUserParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddANewUserParamsWithTimeout creates a new AddANewUserParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddANewUserParamsWithTimeout(timeout time.Duration) *AddANewUserParams {
	var ()
	return &AddANewUserParams{

		timeout: timeout,
	}
}

// NewAddANewUserParamsWithContext creates a new AddANewUserParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddANewUserParamsWithContext(ctx context.Context) *AddANewUserParams {
	var ()
	return &AddANewUserParams{

		Context: ctx,
	}
}

// NewAddANewUserParamsWithHTTPClient creates a new AddANewUserParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddANewUserParamsWithHTTPClient(client *http.Client) *AddANewUserParams {
	var ()
	return &AddANewUserParams{
		HTTPClient: client,
	}
}

/*AddANewUserParams contains all the parameters to send to the API endpoint
for the add a new user operation typically these are written to a http.Request
*/
type AddANewUserParams struct {

	/*Body
	  User definition

	*/
	Body *models.User

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add a new user params
func (o *AddANewUserParams) WithTimeout(timeout time.Duration) *AddANewUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add a new user params
func (o *AddANewUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add a new user params
func (o *AddANewUserParams) WithContext(ctx context.Context) *AddANewUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add a new user params
func (o *AddANewUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add a new user params
func (o *AddANewUserParams) WithHTTPClient(client *http.Client) *AddANewUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add a new user params
func (o *AddANewUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add a new user params
func (o *AddANewUserParams) WithBody(body *models.User) *AddANewUserParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add a new user params
func (o *AddANewUserParams) SetBody(body *models.User) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AddANewUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
