// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostUserReader is a Reader for the PostUser structure.
type PostUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostUserCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostUserBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostUserCreated creates a PostUserCreated with default headers values
func NewPostUserCreated() *PostUserCreated {
	return &PostUserCreated{}
}

/*PostUserCreated handles this case with default header values.

Created
*/
type PostUserCreated struct {
}

func (o *PostUserCreated) Error() string {
	return fmt.Sprintf("[POST /users][%d] postUserCreated ", 201)
}

func (o *PostUserCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostUserBadRequest creates a PostUserBadRequest with default headers values
func NewPostUserBadRequest() *PostUserBadRequest {
	return &PostUserBadRequest{}
}

/*PostUserBadRequest handles this case with default header values.

Bad Request
*/
type PostUserBadRequest struct {
}

func (o *PostUserBadRequest) Error() string {
	return fmt.Sprintf("[POST /users][%d] postUserBadRequest ", 400)
}

func (o *PostUserBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
